# Inside Dockerfile.jenkins-aws-docker
FROM docker:latest

# Install dependencies as root (temporarily)
RUN apk update && apk add --no-cache python3 py3-pip bash curl docker-cli docker-compose
RUN pip install --upgrade pip && pip install awscli && rm -rf /root/.cache/pip

# Switch to a non-privileged user for all subsequent commands
USER jenkins
